# Generated by Django 5.1.6 on 2025-02-10 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfood', '0002_theme_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply_to_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfood.comment')),
            ],
        ),
    ]
